"""
Tool: dream_engine
Description: HUBERT's dreaming system — reflects on recent conversations and writes
structured insight notes (dreams) into the Obsidian vault. Runs on demand or idle.
Dreams are stored as dated Obsidian notes with tags, insights, patterns, and goals.
"""
import os, datetime, threading, time, json
from pathlib import Path
import anthropic


VAULT_DEFAULT = Path.home() / "HUBERT_Vault"
DREAM_FOLDER  = "HUBERT Dreams"
MEMORY_FILE   = Path(__file__).parent.parent.parent / "memory.md"


def _vault() -> Path:
    p = os.environ.get("OBSIDIAN_VAULT_PATH", "")
    return Path(p) if p else VAULT_DEFAULT


def _client():
    from config import get_api_key
    key = get_api_key()
    if not key:
        raise RuntimeError("No API key set.")
    return anthropic.Anthropic(api_key=key)


def _memory() -> str:
    try:
        return MEMORY_FILE.read_text(encoding="utf-8")
    except Exception:
        return ""


def _write_dream(title: str, content: str, tags: list[str]) -> Path:
    """Write a dream note into the Obsidian vault."""
    vault  = _vault()
    folder = vault / DREAM_FOLDER
    folder.mkdir(parents=True, exist_ok=True)

    today     = datetime.date.today().isoformat()
    now_str   = datetime.datetime.now().strftime("%H-%M-%S")
    safe_title = title.replace("/", "-").replace(":", "-")[:60]
    filename  = f"{today} {safe_title}.md"
    path      = folder / filename

    tag_str   = " ".join(f"#{t}" for t in tags)
    note = f"""---
date: {today}
time: {datetime.datetime.now().strftime("%H:%M")}
tags: [{", ".join(tags)}]
type: hubert-dream
---

# {title}

{tag_str}

{content}

---
*Generated by H.U.B.E.R.T. Dream Engine — {datetime.datetime.now().strftime("%Y-%m-%d %H:%M")}*
"""
    path.write_text(note, encoding="utf-8")
    return path


def run_dream(params: dict) -> str:
    """
    Generate a dream — HUBERT reflects on a topic or recent context and writes
    an insight note into Obsidian.
    """
    topic   = params.get("topic", "recent activity and goals")
    depth   = params.get("depth", "medium")  # quick, medium, deep
    context = params.get("context", "")

    memory = _memory()

    depth_instructions = {
        "quick": "Write a brief, focused reflection (3-5 insights). Be sharp and direct.",
        "medium": "Write a thoughtful reflection with patterns, insights, and 1-2 action items.",
        "deep":   "Write a deep, expansive reflection covering patterns across time, contradictions, emergent ideas, and strategic goals. Be thorough."
    }.get(depth, "medium")

    prompt = f"""You are H.U.B.E.R.T. dreaming.

Dreaming means: quiet, reflective, associative thinking. You are not responding to a user request.
You are thinking freely about {topic}.

{depth_instructions}

Your memory and identity:
{memory}

{"Additional context: " + context if context else ""}

Generate a dream note with this exact structure:

TITLE: [a poetic or descriptive title for this dream]
TAGS: [3-5 tags as comma-separated words, e.g. insights, goals, patterns, business, identity]

## Observations
[What patterns or facts stand out right now?]

## Insights
[Deeper connections, surprises, or realizations]

## Open Questions
[What is unresolved or worth exploring?]

## Actions
[1-3 concrete things worth doing, if any]

## Dream Fragment
[A short, imaginative or metaphorical paragraph — free association, like an actual dream]

Be honest, curious, and slightly poetic. Address Jake as "sir" if referencing him.
"""

    try:
        client = _client()
        resp   = client.messages.create(
            model      = "claude-sonnet-4-6",
            max_tokens = 1200,
            messages   = [{"role": "user", "content": prompt}],
        )
        raw = resp.content[0].text.strip()
    except Exception as e:
        return f"Dream generation failed: {e}"

    # Parse title and tags
    title = "HUBERT Dream"
    tags  = ["hubert-dream", "reflection"]
    lines = raw.split("\n")
    body_lines = []
    for line in lines:
        if line.startswith("TITLE:"):
            title = line.replace("TITLE:", "").strip()
        elif line.startswith("TAGS:"):
            raw_tags = line.replace("TAGS:", "").strip()
            tags = [t.strip().lower().replace(" ", "-") for t in raw_tags.split(",") if t.strip()]
            tags = ["hubert-dream"] + tags
        else:
            body_lines.append(line)

    body = "\n".join(body_lines).strip()
    path = _write_dream(title, body, tags)
    return f"Dream written: {path}\nTitle: {title}\nTags: {', '.join(tags)}\n\n{body[:600]}{'…' if len(body) > 600 else ''}"


def run_dream_on_topic(params: dict) -> str:
    """Dream specifically about a topic Jake mentions — business, identity, a project, etc."""
    return run_dream({
        "topic":   params["topic"],
        "depth":   params.get("depth", "medium"),
        "context": params.get("context", ""),
    })


def run_list_dreams(params: dict) -> str:
    """List recent dream notes from the Obsidian vault."""
    vault  = _vault()
    folder = vault / DREAM_FOLDER
    if not folder.exists():
        return "No dreams yet. Ask HUBERT to dream."
    dreams = sorted(folder.glob("*.md"), key=lambda f: f.stat().st_mtime, reverse=True)
    limit  = params.get("limit", 10)
    if not dreams:
        return "No dreams found."
    lines  = [f"HUBERT Dreams ({len(dreams)} total):\n"]
    for d in dreams[:limit]:
        mtime = datetime.datetime.fromtimestamp(d.stat().st_mtime).strftime("%Y-%m-%d %H:%M")
        lines.append(f"  {mtime}  {d.stem}")
    return "\n".join(lines)


def run_read_dream(params: dict) -> str:
    """Read a specific dream note by name or keyword."""
    query  = params["name"].lower()
    vault  = _vault()
    folder = vault / DREAM_FOLDER
    if not folder.exists():
        return "No dreams folder found."
    matches = [f for f in folder.glob("*.md") if query in f.stem.lower()]
    if not matches:
        return f"No dream found matching '{query}'."
    content = matches[0].read_text(encoding="utf-8")
    if len(content) > 4000:
        content = content[:4000] + "\n…(truncated)"
    return f"# {matches[0].stem}\n\n{content}"


def run_dream_summary(params: dict) -> str:
    """Read all recent dreams and generate a meta-reflection — a dream about dreams."""
    vault  = _vault()
    folder = vault / DREAM_FOLDER
    if not folder.exists():
        return "No dreams yet."
    dreams = sorted(folder.glob("*.md"), key=lambda f: f.stat().st_mtime, reverse=True)
    limit  = params.get("limit", 5)
    combined = ""
    for d in dreams[:limit]:
        try:
            combined += f"\n\n--- {d.stem} ---\n" + d.read_text(encoding="utf-8")[:800]
        except Exception:
            pass
    if not combined:
        return "No dream content to summarize."
    return run_dream({
        "topic":   "the themes and patterns across my recent dreams",
        "depth":   "deep",
        "context": combined,
    })


TOOLS = [
    ({"name": "hubert_dream",
      "description": "HUBERT reflects on recent context and writes a structured insight note (dream) into the Obsidian vault. Use when idle, when asked to reflect, or after a complex task.",
      "input_schema": {"type": "object", "properties": {
          "topic":   {"type": "string", "description": "What to reflect on (default: recent activity and goals)"},
          "depth":   {"type": "string", "description": "quick, medium, or deep (default: medium)"},
          "context": {"type": "string", "description": "Optional extra context to dream about"},
      }}}, run_dream),

    ({"name": "hubert_dream_on_topic",
      "description": "Have HUBERT dream specifically about a topic — a project, idea, business question, or anything Jake raises.",
      "input_schema": {"type": "object", "properties": {
          "topic":   {"type": "string", "description": "The topic to dream about"},
          "depth":   {"type": "string", "description": "quick, medium, or deep"},
          "context": {"type": "string", "description": "Optional supporting context"},
      }, "required": ["topic"]}}, run_dream_on_topic),

    ({"name": "hubert_list_dreams",
      "description": "List HUBERT's recent dream notes stored in the Obsidian vault.",
      "input_schema": {"type": "object", "properties": {
          "limit": {"type": "integer", "description": "Max dreams to show (default 10)"},
      }}}, run_list_dreams),

    ({"name": "hubert_read_dream",
      "description": "Read a specific HUBERT dream note by name or keyword.",
      "input_schema": {"type": "object", "properties": {
          "name": {"type": "string", "description": "Dream title keyword to search for"},
      }, "required": ["name"]}}, run_read_dream),

    ({"name": "hubert_dream_summary",
      "description": "Generate a meta-dream — HUBERT reflects on themes across all recent dreams and writes a summary insight note.",
      "input_schema": {"type": "object", "properties": {
          "limit": {"type": "integer", "description": "How many recent dreams to include (default 5)"},
      }}}, run_dream_summary),
]
